apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: np-service-user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: np-service-user
    spec:
      containers:
      - name: np-service-user
        image: navalprabhakar/np-service-user:0.0.1-Snapshot
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
