apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: np-service-order
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: np-service-order
    spec:
      containers:
      - name: np-service-order
        image: navalprabhakar/np-service-order:0.0.1-Snapshot
        ports:
        - containerPort: 9092
