---
apiVersion: v1
kind: Service
metadata:
  name: np-service-userorder
  labels:
    app: np-service-userorder
spec:
  type: NodePort
  selector:
    app: np-service-userorder
  ports:
  - protocol: TCP
    port: 9090
    name: http
