apiVersion: v1
kind: ConfigMap
metadata:
  name: np-service-userorder
  labels:
    app: np-service-userorder
data:
  application.properties: |-
    spring.application.name=np-service-userorder
    spring.profiles.active=k8s
    server.port=9090
    spring.cloud.kubernetes.reload.enabled=true 
    management.endpoint.restart.enabled = true
    server.compression.enabled=true
    
    external.url.service.user=http://127.0.0.1:9091/users
    external.url.service.order=http://127.0.0.1:9092/orders/all


